configuration: Release
image: Visual Studio 2015
platform: Any CPU

assembly_info:
  patch: true
  file: src\ElasticEngine\Properties\AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  #- nuget restore

build:
  parallel: true
  project: src\ElasticEngine.sln   
